-- Gestión de maquinas

-- Creamos Tabla Rol
CREATE TABLE ROL (
    ID_ROL NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(30) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200)
);

-- 2. Creamos Tabla Usuario
CREATE TABLE USUARIO (
    ID_USUARIO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    EMAIL VARCHAR2(100) NOT NULL UNIQUE,
    CONTRASENA VARCHAR2(200) NOT NULL,
    ID_ROL NUMBER NOT NULL,
    FECHA_REGISTRO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_USUARIO_ROL FOREIGN KEY (ID_ROL) REFERENCES ROL(ID_ROL)
);

-- 3. Creamos Tabla Categoria
CREATE TABLE CATEGORIA (
    ID_CATEGORIA NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(50) NOT NULL UNIQUE,
    DESCRIPCION VARCHAR2(200)
);

-- 4. Creamos Tabla Proveedor
CREATE TABLE PROVEEDOR (
    ID_PROVEEDOR NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    CONTACTO VARCHAR2(100),
    TELEFONO VARCHAR2(20),
    EMAIL VARCHAR2(100) UNIQUE,
    DIRECCION VARCHAR2(200)
);

-- 5. Creamos Tabla Producto
CREATE TABLE PRODUCTO (
    ID_PRODUCTO NUMBER PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    ID_CATEGORIA NUMBER NOT NULL,
    ID_PROVEEDOR NUMBER NOT NULL,
    PRECIO_COSTO NUMBER(10,2) NOT NULL,
    PORCENTAJE_GANANCIA NUMBER(5,2) DEFAULT 30,
    PRECIO_VENTA NUMBER(10,2),
    STOCK_BODEGA NUMBER DEFAULT 0,
    FECHA_INGRESO DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PRODUCTO_CATEGORIA FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
    CONSTRAINT FK_PRODUCTO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    CONSTRAINT CK_PRECIO_COSTO CHECK (PRECIO_COSTO > 0),
    CONSTRAINT CK_PORCENTAJE CHECK (PORCENTAJE_GANANCIA BETWEEN 0 AND 300)
);

-- 6. Creamos Tabla Maquina
CREATE TABLE MAQUINA (
    ID_MAQUINA NUMBER PRIMARY KEY,
    CODIGO_MAQUINA VARCHAR2(50) NOT NULL UNIQUE,
    UBICACION VARCHAR2(200) NOT NULL,
    CAPACIDAD_MAXIMA NUMBER DEFAULT 100,
    ESTADO VARCHAR2(20) NOT NULL,
    FECHA_INSTALACION DATE DEFAULT SYSDATE,
    CONSTRAINT CK_MAQUINA_ESTADO CHECK (ESTADO IN ('ACTIVA', 'INACTIVA', 'MANTENIMIENTO'))
);

-- 7. Creamos Tabla producto_Maquina (relación muchos a muchos)
CREATE TABLE PRODUCTO_MAQUINA (
    ID_PRODUCTO_MAQUINA NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    ID_MAQUINA NUMBER NOT NULL,
    STOCK_ACTUAL NUMBER DEFAULT 0,
    STOCK_MINIMO NUMBER DEFAULT 5,
    FECHA_ASIGNACION DATE DEFAULT SYSDATE,
    CONSTRAINT FK_PM_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_PM_MAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA(ID_MAQUINA),
    CONSTRAINT UK_PRODUCTO_MAQUINA UNIQUE (ID_PRODUCTO, ID_MAQUINA),
    CONSTRAINT CK_STOCK_MINIMO CHECK (STOCK_MINIMO >= 0)
);

-- 8. Creamos Tabla Pedido
CREATE TABLE PEDIDO (
    ID_PEDIDO NUMBER PRIMARY KEY,
    ID_PROVEEDOR NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    FECHA_PEDIDO DATE DEFAULT SYSDATE,
    FECHA_RECEPCION DATE,
    ESTADO VARCHAR2(20) DEFAULT 'PENDIENTE',
    TOTAL NUMBER(12,2) DEFAULT 0,
    CONSTRAINT FK_PEDIDO_PROVEEDOR FOREIGN KEY (ID_PROVEEDOR) REFERENCES PROVEEDOR(ID_PROVEEDOR),
    CONSTRAINT FK_PEDIDO_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_PEDIDO_ESTADO CHECK (ESTADO IN ('PENDIENTE', 'RECIBIDO', 'CANCELADO'))
);

-- 9. Creamos Tabla Detalle_Pedido
CREATE TABLE DETALLE_PEDIDO (
    ID_DETALLE NUMBER PRIMARY KEY,
    ID_PEDIDO NUMBER NOT NULL,
    ID_PRODUCTO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    SUBTOTAL NUMBER(12,2),
    CONSTRAINT FK_DETALLE_PEDIDO FOREIGN KEY (ID_PEDIDO) REFERENCES PEDIDO(ID_PEDIDO),
    CONSTRAINT FK_DETALLE_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT CK_CANTIDAD CHECK (CANTIDAD > 0)
);

-- 10. Creamos Tabla MOVIMIENTO_INVENTARIO
CREATE TABLE MOVIMIENTO_INVENTARIO (
    ID_MOVIMIENTO NUMBER PRIMARY KEY,
    ID_PRODUCTO NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    ID_MAQUINA NUMBER,
    TIPO_MOVIMIENTO VARCHAR2(30) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    FECHA DATE DEFAULT SYSDATE,
    CONSTRAINT FK_MOV_PRODUCTO FOREIGN KEY (ID_PRODUCTO) REFERENCES PRODUCTO(ID_PRODUCTO),
    CONSTRAINT FK_MOV_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT FK_MOV_MAQUINA FOREIGN KEY (ID_MAQUINA) REFERENCES MAQUINA(ID_MAQUINA),
    CONSTRAINT CK_TIPO_MOVIMIENTO CHECK (TIPO_MOVIMIENTO IN ('ENTRADA POR PEDIDO', 'RECARGA A MAQUINA', 'VENTA EN MAQUINA', 'AJUSTE MANUAL'))
);

-- 11. Creamos Tabla Venta
CREATE TABLE VENTA (
    ID_VENTA NUMBER PRIMARY KEY,
    ID_PRODUCTO_MAQUINA NUMBER NOT NULL,
    ID_USUARIO NUMBER NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    PRECIO_UNITARIO NUMBER(10,2) NOT NULL,
    TOTAL NUMBER(12,2),
    FECHA_VENTA DATE DEFAULT SYSDATE,
    CONSTRAINT FK_VENTA_PM FOREIGN KEY (ID_PRODUCTO_MAQUINA) REFERENCES PRODUCTO_MAQUINA(ID_PRODUCTO_MAQUINA),
    CONSTRAINT FK_VENTA_USUARIO FOREIGN KEY (ID_USUARIO) REFERENCES USUARIO(ID_USUARIO),
    CONSTRAINT CK_VENTA_CANTIDAD CHECK (CANTIDAD > 0)
);


--Table ROL creado.
--
--
--Table USUARIO creado.
--
--
--Table CATEGORIA creado.
--
--
--Table PROVEEDOR creado.
--
--
--Table PRODUCTO creado.
--
--
--Table MAQUINA creado.
--
--
--Table PRODUCTO_MAQUINA creado.
--
--
--Table PEDIDO creado.
--
--
--Table DETALLE_PEDIDO creado.
--
--
--Table MOVIMIENTO_INVENTARIO creado.
--
--
--Table VENTA creado.
--
-->>Query Run In:Resultado de la Consulta


--Creamos las secuencias

CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PROVEEDOR START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MAQUINA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PRODUCTO_MAQUINA START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_MOVIMIENTO START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE SEQ_VENTA START WITH 1 INCREMENT BY 1;


--Sequence SEQ_ROL creado.
--
--
--Sequence SEQ_USUARIO creado.
--
--
--Sequence SEQ_CATEGORIA creado.
--
--
--Sequence SEQ_PROVEEDOR creado.
--
--
--Sequence SEQ_PRODUCTO creado.
--
--
--Sequence SEQ_MAQUINA creado.
--
--
--Sequence SEQ_PRODUCTO_MAQUINA creado.
--
--
--Sequence SEQ_PEDIDO creado.
--
--
--Sequence SEQ_DETALLE_PEDIDO creado.
--
--
--Sequence SEQ_MOVIMIENTO creado.
--
--
--Sequence SEQ_VENTA creado.
--
-->>Query Run In:Resultado de la Consulta


-- Insertamos datos básicos.


-- roles
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'ADMINISTRADOR', 'Acceso total al sistema');
INSERT INTO ROL (ID_ROL, NOMBRE, DESCRIPCION) VALUES (SEQ_ROL.NEXTVAL, 'COLABORADOR', 'Acceso limitado - solo consultas y pedidos');

-- usuario administrador 
INSERT INTO USUARIO (ID_USUARIO, NOMBRE, EMAIL, CONTRASENA, ID_ROL, FECHA_REGISTRO)
VALUES (SEQ_USUARIO.NEXTVAL, 'Administrador', 'admin@vending.com', 'admin123', 1, SYSDATE);

-- categorías
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (SEQ_CATEGORIA.NEXTVAL, 'BEBIDAS FRIAS', 'Gaseosas, aguas, jugos');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (SEQ_CATEGORIA.NEXTVAL, 'BEBIDAS CALIENTES', 'Café, té, chocolate');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (SEQ_CATEGORIA.NEXTVAL, 'SNACKS SALADOS', 'Papas, nachos, galletas saladas');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (SEQ_CATEGORIA.NEXTVAL, 'SNACKS DULCES', 'Barras de cereal, dulces');
INSERT INTO CATEGORIA (ID_CATEGORIA, NOMBRE, DESCRIPCION) VALUES (SEQ_CATEGORIA.NEXTVAL, 'HIGIENE PERSONAL', 'Toallas húmedas, gel antibacterial');

-- Insertar proveedores de ejemplo
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, CONTACTO, TELEFONO, EMAIL, DIRECCION)
VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Distribuidora Central', 'Carlos Rodríguez', '2255-1234', 'ventas@central.com', 'San José');
INSERT INTO PROVEEDOR (ID_PROVEEDOR, NOMBRE, CONTACTO, TELEFONO, EMAIL, DIRECCION)
VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Alimentos S.A.', 'María González', '2244-5678', 'mg@alimentos.com', 'Heredia');

-- productos
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, ID_CATEGORIA, ID_PROVEEDOR, PRECIO_COSTO, PORCENTAJE_GANANCIA, STOCK_BODEGA)
VALUES (SEQ_PRODUCTO.NEXTVAL, 'Coca Cola 355ml', 1, 1, 350, 30, 500);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, ID_CATEGORIA, ID_PROVEEDOR, PRECIO_COSTO, PORCENTAJE_GANANCIA, STOCK_BODEGA)
VALUES (SEQ_PRODUCTO.NEXTVAL, 'Papas Lay''s 45g', 3, 2, 280, 25, 300);
INSERT INTO PRODUCTO (ID_PRODUCTO, NOMBRE, ID_CATEGORIA, ID_PROVEEDOR, PRECIO_COSTO, PORCENTAJE_GANANCIA, STOCK_BODEGA)
VALUES (SEQ_PRODUCTO.NEXTVAL, 'Agua Cristal 500ml', 1, 1, 250, 20, 1000);

-- máquinas
INSERT INTO MAQUINA (ID_MAQUINA, CODIGO_MAQUINA, UBICACION, CAPACIDAD_MAXIMA, ESTADO, FECHA_INSTALACION)
VALUES (SEQ_MAQUINA.NEXTVAL, 'VM-001', 'Parada de buses - San José', 200, 'ACTIVA', SYSDATE);
INSERT INTO MAQUINA (ID_MAQUINA, CODIGO_MAQUINA, UBICACION, CAPACIDAD_MAXIMA, ESTADO, FECHA_INSTALACION)
VALUES (SEQ_MAQUINA.NEXTVAL, 'VM-002', 'Centro Comercial Paseo Colón', 150, 'ACTIVA', SYSDATE);

-- productos a máquinas
INSERT INTO PRODUCTO_MAQUINA (ID_PRODUCTO_MAQUINA, ID_PRODUCTO, ID_MAQUINA, STOCK_ACTUAL, STOCK_MINIMO)
VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 1, 1, 50, 10);
INSERT INTO PRODUCTO_MAQUINA (ID_PRODUCTO_MAQUINA, ID_PRODUCTO, ID_MAQUINA, STOCK_ACTUAL, STOCK_MINIMO)
VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 2, 1, 30, 8);
INSERT INTO PRODUCTO_MAQUINA (ID_PRODUCTO_MAQUINA, ID_PRODUCTO, ID_MAQUINA, STOCK_ACTUAL, STOCK_MINIMO)
VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 1, 2, 20, 10);

COMMIT;


--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--
--1 fila insertadas.
--
--Confirmación terminada.
-->>Query Run In:Resultado de la Consulta



CREATE OR REPLACE PROCEDURE SP_LISTAR_MAQUINAS(
    p_cursor OUT SYS_REFCURSOR
)
AS
BEGIN
    OPEN p_cursor FOR
        SELECT ID_MAQUINA,
               CODIGO_MAQUINA,
               UBICACION,
               CAPACIDAD_MAXIMA,
               ESTADO,
               TO_CHAR(FECHA_INSTALACION, 'DD/MM/YYYY') AS FECHA_INSTALACION
        FROM MAQUINA
        ORDER BY ID_MAQUINA;
END SP_LISTAR_MAQUINAS;
/

--Procedure SP_LISTAR_MAQUINAS compilado

SET SERVEROUTPUT ON;

DECLARE
    v_cursor SYS_REFCURSOR;
    v_id NUMBER;
    v_codigo VARCHAR2(50);
    v_ubicacion VARCHAR2(200);
    v_capacidad NUMBER;
    v_estado VARCHAR2(20);
    v_fecha VARCHAR2(20);
BEGIN
    SP_LISTAR_MAQUINAS(v_cursor);
    DBMS_OUTPUT.PUT_LINE('*** LISTADO DE MÁQUINAS ***');
    LOOP
        FETCH v_cursor INTO v_id, v_codigo, v_ubicacion, v_capacidad, v_estado, v_fecha;
        EXIT WHEN v_cursor%NOTFOUND;
        DBMS_OUTPUT.PUT_LINE(v_id || ' | ' || v_codigo || ' | ' || v_ubicacion || ' | ' || v_estado);
    END LOOP;
    CLOSE v_cursor;
END;
/

--*** LISTADO DE MÁQUINAS ***
--1 | VM-001 | Parada de buses - San José | ACTIVA
--2 | VM-002 | Centro Comercial Paseo Colón | ACTIVA
--
--Procedimiento PL/SQL terminado correctamente.

