CREATE TABLESPACE VENDING_DATA
DATAFILE 'C:\ORACLE\ORADATA\ORCL\vending_data.dbf'
SIZE 100M
AUTOEXTEND ON NEXT 10M MAXSIZE 500M;

CREATE USER VENDING_USER IDENTIFIED BY "Vending2026$"
DEFAULT TABLESPACE VENDING_DATA;

GRANT CONNECT, RESOURCE TO vending_user;

GRANT ALTER ANY INDEX, ALTER ANY SEQUENCE, 
      ALTER ANY TABLE, CREATE SESSION TO vending_user;

ALTER USER vending_user QUOTA 100M ON vending_data;

SELECT * FROM DBA_USERS
WHERE USERNAME = 'VENDING_USER';

SELECT TABLESPACE_NAME
FROM DBA_TABLESPACES 
WHERE TABLESPACE_NAME = 'VENDING_DATA';

SELECT GRANTED_ROLE FROM DBA_ROLE_PRIVS 
WHERE GRANTEE = 'VENDING_USER';
