
--Funcion para validar que el correo tenga el formato correcto
CREATE OR REPLACE FUNCTION FN_VALIDAR_EMAIL(VEMAIL IN VARCHAR2)
RETURN NUMBER
AS
BEGIN
    IF REGEXP_LIKE(VEMAIL, '^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\.[A-Za-z]{2,}$') THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;




-- Aqui se valida que el telefono tenga el formato 0000-0000
CREATE OR REPLACE FUNCTION FN_VALIDAR_TELEFONO(VTEL IN VARCHAR2)
RETURN NUMBER
AS
BEGIN
    IF REGEXP_LIKE(VTEL, '^[0-9]{4}-[0-9]{4}$') THEN
        RETURN 1;
    ELSE
        RETURN 0;
    END IF;
END;




-- Esta es la funcion que calcula el precio de venta cuando se agrega un nuevo producto
CREATE OR REPLACE FUNCTION FN_CALCULAR_PRECIO(
    VCOSTO IN NUMBER,
    VGANANCIA IN NUMBER
)
RETURN NUMBER
AS
    VPRECIO NUMBER;
BEGIN
    VPRECIO := VCOSTO * (1 + VGANANCIA / 100) * 1.13; --Esto asumiendo el 13% de IVA
    RETURN VPRECIO;
END;

--Prueba
SELECT FN_CALCULAR_PRECIO(500, 30) FROM DUAL;

--Consola
734,5




--Listar categorias y proveedores para saber cuales hay cuando se agregre un nuevo producto
CREATE OR REPLACE FUNCTION FN_LISTAR_CATEGORIAS
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT ID_CATEGORIA, NOMBRE
        FROM CATEGORIA
        ORDER BY NOMBRE;
    RETURN VDATOS;
END;

CREATE OR REPLACE FUNCTION FN_LISTAR_PROVEEDORES
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT ID_PROVEEDOR, NOMBRE
        FROM PROVEEDOR
        ORDER BY NOMBRE;
    RETURN VDATOS;
END;



--La funcion para listar los productos
CREATE OR REPLACE FUNCTION FN_LISTAR_PRODUCTOS
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT P.ID_PRODUCTO, P.NOMBRE, C.NOMBRE AS CATEGORIA, 
               PR.NOMBRE AS PROVEEDOR, P.STOCK_BODEGA, P.PRECIO_VENTA
        FROM PRODUCTO P
        JOIN CATEGORIA C ON P.ID_CATEGORIA = C.ID_CATEGORIA
        JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
        ORDER BY P.NOMBRE;
    RETURN VDATOS;
END;



-- La funcion que llama al SP y retorna el cursor a Java
CREATE OR REPLACE FUNCTION SP_BUSCAR_PRODUCTOS(VCRITERIO IN VARCHAR2)
RETURN SYS_REFCURSOR
AS
    DATOS SYS_REFCURSOR;
BEGIN
    SP_CUR_BUSCAR_PRODUCTOS(DATOS, VCRITERIO);
    RETURN DATOS;
END;



-- Funcion para traer un producto por ID al dialog de editar
CREATE OR REPLACE FUNCTION FN_OBTENER_PRODUCTO(VID IN NUMBER)
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT P.ID_PRODUCTO, P.NOMBRE, C.NOMBRE AS CATEGORIA,
               PR.NOMBRE AS PROVEEDOR, P.PRECIO_COSTO,
               P.PORCENTAJE_GANANCIA, P.PRECIO_VENTA, P.STOCK_BODEGA
        FROM PRODUCTO P
        JOIN CATEGORIA C ON P.ID_CATEGORIA = C.ID_CATEGORIA
        JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
        WHERE P.ID_PRODUCTO = VID;
    RETURN VDATOS;
END;

-- Funcion para Listar pedidos e historial de pedidos
CREATE OR REPLACE FUNCTION FN_LISTAR_PEDIDOS_PENDIENTES
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT P.ID_PEDIDO,
               PR.NOMBRE AS NOMBRE_PROVEEDOR,
               TO_CHAR(P.FECHA_PEDIDO, 'DD-MM-YYYY') AS FECHA,
               P.TOTAL,
               P.ESTADO
        FROM PEDIDO P
        JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
        WHERE P.ESTADO = 'Pendiente'
        ORDER BY P.FECHA_PEDIDO DESC;
    RETURN VDATOS;
END;

CREATE OR REPLACE FUNCTION FN_LISTAR_HISTORIAL_PEDIDOS
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT P.ID_PEDIDO,
               PR.NOMBRE AS NOMBRE_PROVEEDOR,
               TO_CHAR(P.FECHA_PEDIDO, 'DD-MM-YYYY') AS FECHA,
               P.TOTAL,
               P.ESTADO
        FROM PEDIDO P
        JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
        WHERE P.ESTADO IN ('Recibido', 'Cancelado')
        ORDER BY P.FECHA_PEDIDO DESC;
    RETURN VDATOS;
END;


-- Función que lee el total real del pedido desde la BD
CREATE OR REPLACE FUNCTION FN_OBTENER_TOTAL_PEDIDO(VID_PEDIDO IN NUMBER)
RETURN NUMBER
AS
    VTOTAL NUMBER;
BEGIN
    SELECT NVL(TOTAL, 0) INTO VTOTAL
    FROM PEDIDO
    WHERE ID_PEDIDO = VID_PEDIDO;
    RETURN VTOTAL;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RETURN 0;
END;



CREATE OR REPLACE FUNCTION FN_LISTAR_PRODUCTOS_PROVEEDOR(VID_PROVEEDOR IN NUMBER)
RETURN SYS_REFCURSOR
AS
    VDATOS SYS_REFCURSOR;
BEGIN
    OPEN VDATOS FOR
        SELECT P.ID_PRODUCTO, P.NOMBRE, P.PRECIO_VENTA
        FROM PRODUCTO P
        WHERE P.ID_PROVEEDOR = VID_PROVEEDOR
        ORDER BY P.NOMBRE;
    RETURN VDATOS;
END;


CREATE OR REPLACE FUNCTION FN_CUR_DATOS_RECARGA(
    VID_MAQUINA  IN NUMBER,
    VID_PRODUCTO IN NUMBER
)
RETURN SYS_REFCURSOR
AS
    DATOS SYS_REFCURSOR;
    VSQL  VARCHAR2(800);
BEGIN
    VSQL := 'SELECT M.CODIGO_MAQUINA,
                    P.NOMBRE,
                    P.STOCK_BODEGA,
                    PM.STOCK_ACTUAL,
                    M.CAPACIDAD_MAXIMA,
                    PM.ID_PRODUCTO_MAQUINA
             FROM PRODUCTO_MAQUINA PM
             JOIN PRODUCTO P ON PM.ID_PRODUCTO = P.ID_PRODUCTO
             JOIN MAQUINA  M ON PM.ID_MAQUINA  = M.ID_MAQUINA
             WHERE PM.ID_MAQUINA  = :P1
               AND PM.ID_PRODUCTO = :P2';

    OPEN DATOS FOR VSQL USING VID_MAQUINA, VID_PRODUCTO;
    RETURN DATOS;
END FN_CUR_DATOS_RECARGA;
