-- Secuencias para IDs automáticos de todas las tablas
CREATE SEQUENCE SEQ_ROL START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_USUARIO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_CATEGORIA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PROVEEDOR START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MAQUINA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PRODUCTO_MAQUINA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_DETALLE_PEDIDO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_MOVIMIENTO START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;
CREATE SEQUENCE SEQ_VENTA START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;

DESC ROL;

--Consola:
/*
ID_ROL      NOT NULL NUMBER        
NOMBRE      NOT NULL VARCHAR2(50)  
DESCRIPCION          VARCHAR2(200)
*/

-- Roles
INSERT INTO ROL VALUES (SEQ_ROL.NEXTVAL, 'Administrador', 'Acceso total al sistema');
INSERT INTO ROL VALUES (SEQ_ROL.NEXTVAL, 'Colaborador', 'Acceso limitado');
COMMIT;

SELECT * FROM ROL;

--Consola:
/*
1	Administrador	Acceso total al sistema
2	Colaborador	Acceso limitado
*/

DESC USUARIO;

--Consola:
/*
Name           Null?    Type          
-------------- -------- ------------- 
ID_USUARIO     NOT NULL NUMBER        
NOMBRE         NOT NULL VARCHAR2(100) 
EMAIL          NOT NULL VARCHAR2(100) 
CONTRASENA     NOT NULL VARCHAR2(100) 
ID_ROL         NOT NULL NUMBER        
FECHA_REGISTRO          DATE   
*/


-- Usuario admin
INSERT INTO USUARIO VALUES (SEQ_USUARIO.NEXTVAL, 'Deiby Vargas', 'admin@vending.com', 'admin123', 1, SYSDATE);

-- Usuario colaborador
INSERT INTO USUARIO VALUES (SEQ_USUARIO.NEXTVAL, 'Maria Lopez', 'colaborador@vending.com', 'colab123', 2, SYSDATE);
COMMIT;

SELECT * FROM USUARIO;

--Consola:
/*
1	Deiby Vargas	admin@vending.com	admin123	1	09/03/26
2	Maria Lopez	colaborador@vending.com	colab123	2	09/03/26 
*/

DESC CATEGORIA;

--Consola:
/*
Name         Null?    Type          
------------ -------- ------------- 
ID_CATEGORIA NOT NULL NUMBER        
NOMBRE       NOT NULL VARCHAR2(50)  
DESCRIPCION           VARCHAR2(200) 
*/

-- Categorias
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Bebidas', 'Bebidas frias y calientes');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Snacks', 'Snacks salados y dulces');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Dulces', 'Dulces y chocolates');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Galletas', 'Galletas dulces y saladas');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Energéticas', 'Bebidas energéticas');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Saludables', 'Snacks saludables');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Café', 'Bebidas calientes de café');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Té', 'Bebidas de té');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Lácteos', 'Productos lácteos');
INSERT INTO CATEGORIA VALUES (SEQ_CATEGORIA.NEXTVAL, 'Panadería', 'Productos de panadería');
COMMIT;

SELECT * FROM CATEGORIA;

--Consola:
/*
1	Bebidas	Bebidas frias y calientes
2	Snacks	Snacks salados y dulces
3	Dulces	Dulces y chocolates
*/

DESC PROVEEDOR;

--Consola:
/*
Name         Null?    Type          
------------ -------- ------------- 
ID_PROVEEDOR NOT NULL NUMBER        
NOMBRE       NOT NULL VARCHAR2(100) 
CONTACTO              VARCHAR2(100) 
TELEFONO              VARCHAR2(20)  
EMAIL                 VARCHAR2(100) 
DIRECCION             VARCHAR2(200) 
*/

-- Proveedores
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Distribuidora CR', 'Juan Perez', '8888-1111', 'contacto@distribuidoracr.com', 'San Jose, Costa Rica');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Snacks y Mas', 'Maria Lopez', '8888-2222', 'ventas@snacksymas.com', 'Heredia, Costa Rica');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Bebidas del Norte', 'Carlos Mora', '8888-3333', 'info@bebidasnorte.com', 'Alajuela, Costa Rica');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Distribuciones TicoSnack', 'Luis Ramirez', '8888-4444', 'ventas@ticosnack.com', 'Cartago');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Importadora FreshFood', 'Ana Castillo', '8888-5555', 'contacto@freshfood.com', 'San Jose');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Global Snacks CR', 'Jorge Salas', '8888-6666', 'info@globalsnacks.com', 'Heredia');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Bebidas Premium CR', 'Daniel Rojas', '8888-7777', 'ventas@premiumcr.com', 'Alajuela');
INSERT INTO PROVEEDOR VALUES (SEQ_PROVEEDOR.NEXTVAL, 'Alimentos del Valle', 'Sofia Jimenez', '8888-8888', 'info@valle.com', 'Cartago');
COMMIT;


SELECT * FROM PROVEEDOR;

--Consola:
/*
1	Distribuidora CR	Juan Perez	8888-1111	contacto@distribuidoracr.com	San Jose, Costa Rica
2	Snacks y Mas	Maria Lopez	8888-2222	ventas@snacksymas.com	Heredia, Costa Rica
3	Bebidas del Norte	Carlos Mora	8888-3333	info@bebidasnorte.com	Alajuela, Costa Rica
*/


DESC PRODUCTO;

--Consola:
/*
Name                Null?    Type          
------------------- -------- ------------- 
ID_PRODUCTO         NOT NULL NUMBER        
NOMBRE              NOT NULL VARCHAR2(100) 
ID_CATEGORIA        NOT NULL NUMBER        
ID_PROVEEDOR        NOT NULL NUMBER        
PRECIO_COSTO        NOT NULL NUMBER(10,2)  
PORCENTAJE_GANANCIA          NUMBER(5,2)   
PRECIO_VENTA                 NUMBER(10,2)  
STOCK_BODEGA                 NUMBER        
FECHA_INGRESO                DATE     
*/

-- Productos
INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Coca Cola 350ml', 1, 1, 500, 30, 650, 50, SYSDATE);
INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Agua Pura 500ml', 1, 3, 300, 25, 375, 30, SYSDATE);
INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Papas Lays', 2, 2, 400, 30, 520, 40, SYSDATE);
INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Doritos', 2, 2, 450, 30, 585, 35, SYSDATE);
INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Chocolate Kit Kat', 3, 2, 350, 30, 455, 25, SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Pepsi 355ml',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Bebidas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Bebidas del Norte'),
480,30,624,40,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Fanta Naranja',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Bebidas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Distribuidora CR'),
470,30,611,35,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Red Bull',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Energéticas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Bebidas Premium CR'),
900,40,1260,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Monster',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Energéticas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Bebidas Premium CR'),
850,40,1190,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Pringles',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Snacks'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Global Snacks CR'),
700,35,945,25,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Chifrijo Snack',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Snacks'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Distribuciones TicoSnack'),
650,30,845,20,SYSDATE);


INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Snickers',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Dulces'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Global Snacks CR'),
360,30,468,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'M&M',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Dulces'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Global Snacks CR'),
340,30,442,30,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Oreo',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Galletas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Global Snacks CR'),
400,35,540,30,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Chiky',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Galletas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Distribuciones TicoSnack'),
380,30,494,25,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Ritz',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Galletas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Distribuciones TicoSnack'),
350,30,455,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Barra Granola',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Saludables'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
300,30,390,35,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Mix Nueces',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Saludables'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
600,35,810,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Café Negro',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Café'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
500,30,650,30,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Café Latte',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Café'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
600,30,780,25,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Té Frío',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Té'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
400,25,500,30,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Té Verde',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Té'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
420,25,525,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Leche Chocolate',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Lácteos'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
550,30,715,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Yogurt',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Lácteos'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
500,30,650,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Croissant',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Panadería'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
500,30,650,15,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Pan Dulce',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Panadería'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
400,30,520,20,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Empanada',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Panadería'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Alimentos del Valle'),
450,30,585,15,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Jugo Naranja',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Bebidas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
550,25,687,30,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Jugo Manzana',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Bebidas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Importadora FreshFood'),
530,25,662,25,SYSDATE);

INSERT INTO PRODUCTO VALUES (SEQ_PRODUCTO.NEXTVAL, 'Gatorade',
(SELECT ID_CATEGORIA FROM CATEGORIA WHERE NOMBRE='Bebidas'),
(SELECT ID_PROVEEDOR FROM PROVEEDOR WHERE NOMBRE='Bebidas Premium CR'),
600,30,780,30,SYSDATE);

COMMIT;

SELECT * FROM PRODUCTO;

--Consola:
/*
1	Coca Cola 350ml	1	1	500	30	650	50	10/03/26
2	Agua Pura 500ml	1	3	300	25	375	30	10/03/26
3	Papas Lays	2	2	400	30	520	40	10/03/26
4	Doritos	2	2	450	30	585	35	10/03/26
5	Chocolate Kit Kat	3	2	350	30	455	25	10/03/26  
*/

DESC MAQUINA;

--Consola:
/*
Name              Null?    Type          
----------------- -------- ------------- 
ID_MAQUINA        NOT NULL NUMBER        
CODIGO_MAQUINA    NOT NULL VARCHAR2(20)  
UBICACION         NOT NULL VARCHAR2(100) 
CAPACIDAD_MAXIMA           NUMBER        
ESTADO                     VARCHAR2(20)  
FECHA_INSTALACION          DATE          
*/

-- Maquinas
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'Maquina Central', 'Edificio A - Planta Baja', 'Activa');
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'Maquina Norte', 'Edificio B - Segundo Piso', 'Activa');
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'Maquina Sur', 'Cafeteria Principal', 'Activa');
COMMIT;



DESC MAQUINA;

--Consola:
/*
Name              Null?    Type          
----------------- -------- ------------- 
ID_MAQUINA        NOT NULL NUMBER        
CODIGO_MAQUINA    NOT NULL VARCHAR2(20)  
UBICACION         NOT NULL VARCHAR2(100) 
CAPACIDAD_MAXIMA           NUMBER        
ESTADO                     VARCHAR2(20)  
FECHA_INSTALACION          DATE               
*/

-- Maquinas
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'MAQ-001', 'Edificio A - Planta Baja', 50, 'Activa', SYSDATE);
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'MAQ-002', 'Edificio B - Segundo Piso', 50, 'Activa', SYSDATE);
INSERT INTO MAQUINA VALUES (SEQ_MAQUINA.NEXTVAL, 'MAQ-003', 'Cafeteria Principal', 50, 'Activa', SYSDATE);
COMMIT;

SELECT * FROM MAQUINA;

--Consola:
/*
1	MAQ-001	Edificio A - Planta Baja	50	Activa	10/03/26
2	MAQ-002	Edificio B - Segundo Piso	50	Activa	10/03/26
3	MAQ-003	Cafeteria Principal	50	Activa	10/03/26        
*/

DESC PRODUCTO_MAQUINA;

--Consola:
/*
Name                Null?    Type   
------------------- -------- ------ 
ID_PRODUCTO_MAQUINA NOT NULL NUMBER 
ID_PRODUCTO         NOT NULL NUMBER 
ID_MAQUINA          NOT NULL NUMBER 
STOCK_ACTUAL                 NUMBER 
STOCK_MINIMO        NOT NULL NUMBER 
FECHA_ASIGNACION             DATE         
*/

INSERT INTO PRODUCTO_MAQUINA VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 1, 1, 20, 5, SYSDATE);
INSERT INTO PRODUCTO_MAQUINA VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 2, 1, 15, 5, SYSDATE);
INSERT INTO PRODUCTO_MAQUINA VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 3, 2, 20, 5, SYSDATE);
INSERT INTO PRODUCTO_MAQUINA VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 4, 2, 15, 5, SYSDATE);
INSERT INTO PRODUCTO_MAQUINA VALUES (SEQ_PRODUCTO_MAQUINA.NEXTVAL, 5, 3, 10, 3, SYSDATE);
COMMIT;

SELECT * FROM PRODUCTO_MAQUINA;

--Consola:
/*
1	1	1	20	5	10/03/26
2	2	1	15	5	10/03/26
3	3	2	20	5	10/03/26
4	4	2	15	5	10/03/26
5	5	3	10	3	10/03/26         
*/

DESC PEDIDO;

--Consola:
/*
Name            Null?    Type         
--------------- -------- ------------ 
ID_PEDIDO       NOT NULL NUMBER       
ID_PROVEEDOR    NOT NULL NUMBER       
ID_USUARIO      NOT NULL NUMBER       
FECHA_PEDIDO             DATE         
FECHA_RECEPCION          DATE         
ESTADO                   VARCHAR2(20) 
TOTAL                    NUMBER(10,2)         
*/

INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 1, 1, SYSDATE, NULL, 'Pendiente', 0);
COMMIT;

SELECT * FROM PEDIDO;

--Consola:
/*
1	1	1	10/03/26		Pendiente	0        
*/

DESC DETALLE_PEDIDO;

--Consola:
/*
Name            Null?    Type         
--------------- -------- ------------ 
ID_DETALLE      NOT NULL NUMBER       
ID_PEDIDO       NOT NULL NUMBER       
ID_PRODUCTO     NOT NULL NUMBER       
CANTIDAD        NOT NULL NUMBER       
PRECIO_UNITARIO NOT NULL NUMBER(10,2) 
SUBTOTAL                 NUMBER(10,2)       
*/

INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, 1, 1, 10, 500, 5000);
INSERT INTO DETALLE_PEDIDO VALUES (SEQ_DETALLE_PEDIDO.NEXTVAL, 1, 2, 10, 300, 3000);
COMMIT;

SELECT * FROM DETALLE_PEDIDO;

--Consola:
/*
1	1	1	10	500	5000
2	1	2	10	300	3000      
*/



-- PEDIDOS PENDIENTES (5)
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 1, 1, SYSDATE, NULL, 'Pendiente', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 2, 1, SYSDATE - 1, NULL, 'Pendiente', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 3, 2, SYSDATE - 2, NULL, 'Pendiente', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 4, 1, SYSDATE - 3, NULL, 'Pendiente', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 5, 2, SYSDATE - 4, NULL, 'Pendiente', 0);

-- PEDIDOS RECIBIDOS (6) - Para historial
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 6, 1, SYSDATE - 10, SYSDATE - 8, 'Recibido', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 7, 2, SYSDATE - 15, SYSDATE - 13, 'Recibido', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 1, 1, SYSDATE - 20, SYSDATE - 18, 'Recibido', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 3, 2, SYSDATE - 25, SYSDATE - 23, 'Recibido', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 2, 1, SYSDATE - 30, SYSDATE - 28, 'Recibido', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 8, 2, SYSDATE - 35, SYSDATE - 33, 'Recibido', 0);

-- PEDIDOS CANCELADOS (4) - Para historial
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 4, 2, SYSDATE - 12, NULL, 'Cancelado', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 5, 1, SYSDATE - 18, NULL, 'Cancelado', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 6, 2, SYSDATE - 22, NULL, 'Cancelado', 0);
INSERT INTO PEDIDO VALUES (SEQ_PEDIDO.NEXTVAL, 7, 1, SYSDATE - 40, NULL, 'Cancelado', 0);

COMMIT;

UPDATE PRODUCTO_MAQUINA
SET STOCK_ACTUAL = 1
WHERE ID_PRODUCTO = 1;

COMMIT;

