-- Insertar categirias (Se hizo de primero para poder probar que funcione bien la conexion y el java)
CREATE OR REPLACE PROCEDURE SP_INSERTAR_CATEGORIA(
    VNOMBRE IN VARCHAR2,
    VDESC IN VARCHAR2
)
AS
    VCONT NUMBER;
BEGIN
    SELECT COUNT(*) INTO VCONT
    FROM CATEGORIA
    WHERE UPPER(NOMBRE) = UPPER(VNOMBRE);
    
    IF VCONT > 0 THEN
        RAISE_APPLICATION_ERROR(-20001, 'Ya existe esa categoria');
    END IF;
    
    INSERT INTO CATEGORIA VALUES (
        SEQ_CATEGORIA.NEXTVAL,
        VNOMBRE,
        VDESC
    );
    COMMIT;
END;

-- Una prueba para ver si esta guardando los datos
EXEC SP_INSERTAR_CATEGORIA('Lacteos', 'Leches y quesos');

SELECT * FROM CATEGORIA;





-- Para insertar proveedores

CREATE OR REPLACE PROCEDURE SP_INSERTAR_PROVEEDOR(
    VNOMBRE IN VARCHAR2,
    VCONTACTO IN VARCHAR2,
    VTEL IN VARCHAR2,
    VEMAIL IN VARCHAR2,
    VDIR IN VARCHAR2
)
AS
    VCONT NUMBER;
BEGIN
    -- Validar formato email
    IF FN_VALIDAR_EMAIL(VEMAIL) = 0 THEN
        RAISE_APPLICATION_ERROR(-20002, 'El formato del email no es correcto');
    END IF;

    -- Validar formato telefono
    IF FN_VALIDAR_TELEFONO(VTEL) = 0 THEN
        RAISE_APPLICATION_ERROR(-20003, 'El telefono tiene que ser con el formato XXXX-XXXX');
    END IF;

    -- Verificar que el email no este duplicado
    SELECT COUNT(*) INTO VCONT
    FROM PROVEEDOR
    WHERE UPPER(EMAIL) = UPPER(VEMAIL);

    IF VCONT > 0 THEN
        RAISE_APPLICATION_ERROR(-20004, 'Ya hay un proveedor con ese email');
    END IF;

    INSERT INTO PROVEEDOR VALUES (
        SEQ_PROVEEDOR.NEXTVAL,
        VNOMBRE,
        VCONTACTO,
        VTEL,
        VEMAIL,
        VDIR
    );
    COMMIT;
END;

-- Prueba
EXEC SP_INSERTAR_PROVEEDOR('PepsiCo CR', 'Luis Mora', '8888-4444', 'luis@pepsico.com', 'Cartago, Costa Rica');
SELECT * FROM PROVEEDOR;





-- Para insertar un nuevo producto
CREATE OR REPLACE PROCEDURE SP_INSERTAR_PRODUCTO(
    VNOMBRE IN VARCHAR2,
    VID_CATEGORIA IN NUMBER,
    VID_PROVEEDOR IN NUMBER,
    VPRECIO_COSTO IN NUMBER,
    VPORCENTAJE_GANANCIA IN NUMBER,
    VSTOCK_BODEGA IN NUMBER
)
AS
BEGIN
    INSERT INTO PRODUCTO VALUES (
        SEQ_PRODUCTO.NEXTVAL,
        VNOMBRE,
        VID_CATEGORIA,
        VID_PROVEEDOR,
        VPRECIO_COSTO,
        VPORCENTAJE_GANANCIA,
        FN_CALCULAR_PRECIO(VPRECIO_COSTO, VPORCENTAJE_GANANCIA),
        VSTOCK_BODEGA,
        SYSDATE
    );
    COMMIT;
END;

-- Prueba
EXEC SP_INSERTAR_PRODUCTO('Pepsi 350ml', 1, 1, 450, 30, 40);
SELECT * FROM PRODUCTO;




-- SP para el login, retorna datos del usuario si las credenciales son correctas
CREATE OR REPLACE PROCEDURE SP_LOGIN(
    VEMAIL IN VARCHAR2,
    VPASS IN VARCHAR2,
    VNOMBRE OUT VARCHAR2,
    VROL OUT VARCHAR2,
    VID_ROL OUT NUMBER
)
AS
    VCONT NUMBER;
BEGIN
    -- Se verifica que el usuario si exista
    SELECT COUNT(*) INTO VCONT
    FROM USUARIO U
    JOIN ROL R ON U.ID_ROL = R.ID_ROL
    WHERE UPPER(U.EMAIL) = UPPER(VEMAIL)
    AND U.CONTRASENA = VPASS;
    
    IF VCONT = 0 THEN
        RAISE_APPLICATION_ERROR(-20005, 'Correo o contraseña incorrectos');
    END IF;
    
    -- Si existe, traer los datos
    SELECT U.NOMBRE, R.NOMBRE, R.ID_ROL
    INTO VNOMBRE, VROL, VID_ROL
    FROM USUARIO U
    JOIN ROL R ON U.ID_ROL = R.ID_ROL
    WHERE UPPER(U.EMAIL) = UPPER(VEMAIL)
    AND U.CONTRASENA = VPASS;
    
EXCEPTION
    WHEN OTHERS THEN
        RAISE_APPLICATION_ERROR(-20006, 'Error en el login: ' || SQLERRM);
END;




-- Este SP abre el cursor dinamico
CREATE OR REPLACE PROCEDURE SP_CUR_BUSCAR_PRODUCTOS(
    DATOS OUT SYS_REFCURSOR,
    VCRITERIO IN VARCHAR2
)
AS
    VSQL VARCHAR2(1000);
BEGIN
    VSQL := 'SELECT P.ID_PRODUCTO, P.NOMBRE, C.NOMBRE AS CATEGORIA,
                    PR.NOMBRE AS PROVEEDOR, P.STOCK_BODEGA, P.PRECIO_VENTA
             FROM PRODUCTO P
             JOIN CATEGORIA C ON P.ID_CATEGORIA = C.ID_CATEGORIA
             JOIN PROVEEDOR PR ON P.ID_PROVEEDOR = PR.ID_PROVEEDOR
             WHERE REGEXP_LIKE(P.NOMBRE, :P1, ''i'')
             ORDER BY P.NOMBRE';

    OPEN DATOS FOR VSQL USING VCRITERIO;
END;




-- SP para eliminar, lanza excepcion si tiene stock en maquinas
CREATE OR REPLACE PROCEDURE SP_ELIMINAR_PRODUCTO(VID IN NUMBER)
AS
    VSTOCK NUMBER;
BEGIN
    -- Verifica si tiene stock activo en alguna maquina
    SELECT NVL(SUM(STOCK_ACTUAL), 0) INTO VSTOCK
    FROM PRODUCTO_MAQUINA
    WHERE ID_PRODUCTO = VID;

    IF VSTOCK > 0 THEN
        RAISE_APPLICATION_ERROR(-20010, 
            'No se puede eliminar: el producto tiene stock activo en maquinas.');
    END IF;

    DELETE FROM PRODUCTO WHERE ID_PRODUCTO = VID;
    COMMIT;
END;




CREATE OR REPLACE PROCEDURE SP_ACTUALIZAR_PRODUCTO(
    VID IN NUMBER,
    VNOMBRE IN VARCHAR2,
    VPRECIO_COSTO IN NUMBER,
    VPORCENTAJE_GANANCIA IN NUMBER,
    VSTOCK_BODEGA IN NUMBER
)
AS
BEGIN
    UPDATE PRODUCTO SET
        NOMBRE = VNOMBRE,
        PRECIO_COSTO = VPRECIO_COSTO,
        PORCENTAJE_GANANCIA = VPORCENTAJE_GANANCIA,
        PRECIO_VENTA = FN_CALCULAR_PRECIO(VPRECIO_COSTO, VPORCENTAJE_GANANCIA),
        STOCK_BODEGA = VSTOCK_BODEGA
    WHERE ID_PRODUCTO = VID;
    COMMIT;
END;