-- Trigger que calcula subtotal al insertar detalle
CREATE OR REPLACE TRIGGER TRG_SUBTOTAL_DETALLE
BEFORE INSERT OR UPDATE ON DETALLE_PEDIDO
FOR EACH ROW
BEGIN
    :NEW.SUBTOTAL := :NEW.CANTIDAD * :NEW.PRECIO_UNITARIO;
END;



CREATE OR REPLACE PACKAGE PKG_PEDIDO_TOTAL AS
    TYPE T_IDS IS TABLE OF NUMBER INDEX BY PLS_INTEGER;
    G_IDS T_IDS;
    G_COUNT NUMBER := 0;
END PKG_PEDIDO_TOTAL;

CREATE OR REPLACE TRIGGER TRG_VALIDAR_RECARGA
BEFORE UPDATE OF STOCK_ACTUAL ON PRODUCTO_MAQUINA
FOR EACH ROW
DECLARE
    VCAPACIDAD NUMBER;
BEGIN
    SELECT CAPACIDAD_MAXIMA INTO VCAPACIDAD
    FROM MAQUINA
    WHERE ID_MAQUINA = :NEW.ID_MAQUINA;

    IF :NEW.STOCK_ACTUAL > VCAPACIDAD THEN
        RAISE_APPLICATION_ERROR(-20044,
            'La recarga supera la capacidad máxima de la máquina (' 
            || VCAPACIDAD || ' unidades).');
    END IF;
END;
/

SELECT TRIGGER_NAME, STATUS
FROM USER_TRIGGERS;

SELECT *
FROM USER_ERRORS
WHERE TYPE = 'TRIGGER';